name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt --force-reinstall
      - name: List key packages
        run: |
          pip list | grep -E 'httpx|fastapi|starlette|pytest' || true
          python -c "import sys, httpx; print('httpx module file:', httpx.__file__)"
      - name: Show dependency versions
        run: |
          python -c "import httpx, fastapi, starlette, pytest, json; print(json.dumps({'httpx': httpx.__version__, 'fastapi': fastapi.__version__, 'starlette': starlette.__version__, 'pytest': pytest.__version__}))"
      - name: Run tests (mock mode)
        env:
          USE_MOCK_GEMINI: '1'
        run: pytest -q

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-react
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend-react/package.json
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
